/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 6.0.0   2016-10-17

The MIT License (MIT)
Copyright (c) 2009-2016 Atollic AB

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
******************************************************************************
*/

/* Includes */
#include <stddef.h>
#include <stdio.h>
#include <math.h>
#include "stm32l1xx.h"
#include "vrs_cv5.h"

volatile int switchFormat = 0;
volatile uint32_t AD_value = 0;

int main(void){
  int i = 0;

  led_init();
  AD_value = adc_init();
  nvic_init();
  usart_init();
  
  char numValue[5];
  char volValue[6];

   /* Infinite loop */
  while (1)
  {
	 work(which_button(AD_value));
	 if(switchFormat){
		 // print hodnoty napatia
	 		float voltage = 3.3*(AD_value/4095.0);
	 		int celeCislo = napatie;
	 		float zvysok = voltage - celeCislo;
	 		int desatinneCislo = trunc(zvysok*100);
	 		sprintf(volValue, "%d.%dV", celeCislo, desatinneCislo);

	 		SendUSART2(volValue);
	 		SendUSART2("V\n\r");
	 	}
	 	else{
	 	// print ciselnej hodnoty
	 		sprintf(numValue, "%d", AD_value);
	 		SendUSART2(numValue);
	 		SendUSART2("\n\r");
	 	}
  }
  return 0;
}

void ADC1_IRQHandler(void){
	if(ADC1->SR & ADC_SR_EOC)
		AD_value = ADC1->DR;
}

void USART2_IRQHandler(void) {
	uint8_t tmp = 0;
	if (USART_GetITStatus(USART2, USART_IT_RXNE) != RESET) {
		tmp = USART_ReceiveData(USART2);
		if(tmp == 'm'){
			if(switchFormat) switchFormat = 0;
			else switchFormat = 1;
		}
		USART_ClearITPendingBit(USART2, USART_IT_RXNE);
	}
}

#ifdef  USE_FULL_ASSERT

/**
  * @brief  Reports the name of the source file and the source line number
  *   where the assert_param error has occurred.
  * @param  file: pointer to the source file name
  * @param  line: assert_param error line source number
  * @retval None
  */
void assert_failed(uint8_t* file, uint32_t line)
{
  /* User can add his own implementation to report the file name and line number,
     ex: printf("Wrong parameters value: file %s on line %d\r\n", file, line) */

  /* Infinite loop */
  while (1)
  {
  }
}
#endif

/*
 * Minimal __assert_func used by the assert() macro
 * */
void __assert_func(const char *file, int line, const char *func, const char *failedexpr)
{
  while(1)
  {}
}

/*
 * Minimal __assert() uses __assert__func()
 * */
void __assert(const char *file, int line, const char *failedexpr)
{
   __assert_func (file, line, NULL, failedexpr);
}
